config/routes.rb
Rails.application.routes.draw do
  root 'flats#index'
  resources :flats

  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many :insights
  has_many :rooms
end

app/models/insight.rb
class Insight < ApplicationRecord
  belongs_to :flat
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :flat

  has_attachments :photos, maximum: 8
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
  end

  def create
  end

  def show
    @flat = Flat.find(params[:id])

    @background_photos = [
      "outdoor1", "living1", "cuisine1",
      "outdoor9", "living2", "chambre5",
      "outdoor2", "living4", "outdoor8"
    ]
  end

  def update
  end

  private

  def clean_params
    params.require(:flat).permit(:name, :description, :address, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
  # http://cobwwweb.com/render-inline-svg-rails-middleman
  def svg(name)
    file_path = "#{Rails.root}/app/assets/images/icons/#{name}"
    return File.read(file_path).html_safe if File.exists?(file_path)
    '(not found)'
  end
end

app/views/flats/_room-infos.html.erb
<% @flat.rooms.each_with_index do |room, i| %>
  <div class="col-12 col-lg-6" id="<%= "room#{i}:#{room.name}" %>">
    <div class="room">
      <p class="room-description"><%= room.description %></p>
      <div class="room-images-box row">
        <div class="col-6 text-center">
          <%= image_tag cl_image_path(room.photos[0].path), class: "room-image" %>
        </div>
        <div class="col-6 text-center">
          <%= image_tag cl_image_path(room.photos[1].path), class: "room-image" %>
        </div>
      </div>
      <%= link_to "cliquer pour agrandir les photos", "##{room.name}", class: "room-images-galery-link" %>
    </div>
  </div>
<% end %>

app/views/flats/index.html.erb
<div class="main-content">
  <div class="video-background">
    <div id="video-foreground">
      <iframe id="background-video" width="100%" height="110%" src="https://www.youtube.com/embed/lQbFWZvbS40?rel=0&amp;controls=0&amp;showinfo=0&autoplay=1&loop=1&playlist=lQbFWZvbS40"
       frameborder="0" allowfullscreen></iframe>
    </div>
  </div>
  <div class="header-title">
    <h1 id="homeHeading">Locations aux Chartrons<br>Bordeaux</h1>
    <p class="subtitle">4 appartements dans le centre de Bordeaux pour votre plus grand confort</p>
  </div>
  <section id="insight-list">
    <div class="insight families">
      <%#= image_tag("icons/ic_group_white_48dp_1x") %>
      <p>idéal pour les familles, calme et silencieux</p>
    </div>
    <div class="insight access">
      <%= image_tag("icons/ic_directions_walk_white_48dp_1x") %>
      <p>facile d’accès et près du centre</p>
    </div>
    <div class="insight parking">
      <%= image_tag("icons/ic_time_to_leave_white_48dp_1x") %>
      <p>parking et chauffeur en option</p>
    </div>
    <div class="insight connectivity">
      <%= image_tag("icons/ic_wifi_white_48dp_1x") %>
      <p>connection internet de bonne qualité et tv</p>
    </div>
    <div class="insight reviews">
      <%= image_tag("icons/ic_thumb_up_white_48dp_1x", id: "thumb_up" ) %>
      <p>recommandé par de nombreux avis</p>
      <%= link_to "https://www.airbnb.fr/rooms/6747273#reviews", target: "_blank" do %>
        <%= image_tag("icons/open", id: "open")%>
      <% end %>
    </div>
  </section>
  <%= link_to "https://goo.gl/maps/REQQSxy2d942", id: "staticmap-box" do %>
    <div class="display-hover">cliquer ici pour voir la carte</div>
    <%= image_tag("staticmap", alt: "google-map-static", id: "map") %>
  <% end %>

</div>
<div id="apartments-panel">
  <a id="toggle-panel-right" class="btn btn-xl">
    <%= image_tag "icons/ic_clear_white_48dp_2x" %>
    <span>Voir les locations</span>
  </a>

  <% @flats.each do |flat| %>
  <%= link_to flat_path(flat), class: "apartment", style: "background: linear-gradient(90deg, rgba(119, 119, 119, 0) 40%, rgba(230, 147, 100, 0.34));" do %>
  <p class="title"><%= "#{flat.name} - #{flat.surface}m²" %></p>
  <p class="description"><%= flat.description.first(90) %></p>
  <p class="end-description">(...)</p>
  <p class="underline">cliquer ici pour voir plus de détails</p>
  <div class="filter"></div>
  <%= cl_image_tag("6002bc6b_original_m7lit4") %>
  <% end %>
  <% end %>
  <%= link_to "#", class: "apartment", style: "background: linear-gradient(90deg, rgba(119, 119, 119, 0) 40%, rgba(33, 127, 223, 0.5));" do %>
  <p class="title">Appartement 2</p>
  <p>Détails bientôt disponibles</p>
  <p class="underline">cliquer ici pour voir plus de détails</p>
  <div class="filter"></div>
  <%= cl_image_tag(Flat.all[0].rooms[1].photos.first.public_id) %>
  <% end %>
  <%= link_to "#", class: "apartment", style: "background: linear-gradient(90deg, rgba(119, 119, 119, 0) 40%, rgba(69, 232, 192, .43));" do %>
  <p class="title">Appartement 3</p>
  <p>Détails bientôt disponibles</p>
  <p class="underline">cliquer ici pour voir plus de détails</p>
  <div class="filter"></div>
  <%= cl_image_tag(Flat.all[0].rooms[2].photos[2].public_id) %>
  <% end %>
  <%= link_to "#", class: "apartment", style: "background: linear-gradient(90deg, rgba(119, 119, 119, 0) 40%, rgba(147, 105, 242, 0.5));" do %>
  <p class="title">Appartement 4</p>
  <p>Détails bientôt disponibles</p>
  <p class="underline">cliquer ici pour voir plus de détails</p>
  <div class="filter"></div>
  <%= cl_image_tag(Flat.all[0].rooms[1].photos[2].public_id) %>
  <% end %>
</div>

<%= content_for :after_js do %>
  <script>
    $(document).ready(function(){
      sizeTheVideo();
      $(window).resize(function(){
        sizeTheVideo();
      });
      $('#toggle-panel-right').on('click', function() {
        $('#toggle-panel-right').toggleClass('reduced');
        $('#apartments-panel').toggleClass('expand');
        $('#staticmap-box').toggleClass('d-none');
      });
    });

    function sizeTheVideo(){
      // - 1.78 is the aspect ratio of the video
    // - This will work if your video is 1920 x 1080
    // - To find this value divide the video's native width by the height eg 1920/1080 = 1.78
      var aspectRatio = 1.78;

        var video = $('#video-foreground iframe');
        var videoHeight = video.outerHeight();
        var newWidth = videoHeight*aspectRatio;
    		var halfNewWidth = newWidth/2;

      //Define the new width and centrally align the iframe
      video.css({"width":newWidth+"px","left":"50%","margin-left":"-"+halfNewWidth+"px"});
    }
  </script>
<% end %>

app/views/flats/new.html.erb
<h1>Flats#new</h1>
<p>Find me in app/views/flats/new.html.erb</p>
<%= form_for(Flat.first.rooms.first) do |f| %>

  <%= f.file_field :photos, multiple: true %>
<% end %>

app/views/flats/show.html.erb
<div id="main-content">
  <nav class="navbar navbar-expand-lg navbar-light show" id="secondNav">
    <div class="container-fluid">
      <%= link_to "Retour", flats_path, class: "navbar-brand back", data: { no_turbolink: true } %>
      <p id="disponibility">Actuellement disponible</p>
    </div>
  </nav>

  <div id="carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
      <% 9.times do |t| %>
        <div class="carousel-item">
          <%= image_tag cl_image_path("hcb/42_rue-Binaud/#{@background_photos[t]}.jpg"), class: "image-blur" %>
          <div class="image-box">
            <%= image_tag cl_image_path("hcb/42_rue-Binaud/#{@background_photos[t]}.jpg"), class: "image" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <section id="description-header">
    <div class="apartment">
      <p class="name title"><%= @flat.name %></p>
      <p class="surface title">- 115m²</p>
      <div class="price-box">
        <p class="price">110 €</p>
        <p class="unity">/ par nuit</p>
      </div>
    </div>
    <div id="description-content-insights">
      <p class="description-content container-fluid"><%= @flat.description %></p>
      <div class="insights">
        <div class="row">
          <% @flat.insights.each do |insight| %>
            <div class="insight">
              <p><%= svg(insight.icon_name) %> <%= insight.quantity %> <%= insight.legend %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>

  <section id="rooms-description">
    <button type="button" id="btn-rooms">
      Descriptif complet des pièces
      <span class="fa fa-caret-down" id="arrow" title="expand rooms-description-content">
    </button>

    <div class="" id="rooms-description-content">
      <p class="location-indication">Le logement est situé à 10 minutes à pied des quais et du centre</p>
      <div class="row" id="rooms-container">
        <%= render "room-infos" %>
      </div>
    </div>
  </section>

  <section class="container-fluid" id="rules-extra">
    <div class="row">
      <div class="col-12 col-md-6" id="rules">
        <p class="title">Réglement Intérieur</p>
        <div class="container">
          <p class="rule">Non fumeur</p>
          <p class="rule">Pas d'animaux</p>
          <p class="rule">Pas de fêtes ni de soirées</p>
          <p class="rule">L'entrée dans les lieux se fait à partir de 15:00</p>
        </div>
      </div>
      <div class="col-12 col-md-6 text-center">
        <div id="extra">
          <p>
            Nous vous fournissons les draps et les serviettes de toilette gratuitement !</br>
            Lit parapluie combiné et chaise haute sur demande.
          </p>
        </div>
        <%= link_to "Voir l'emplacement du quartier sur google maps", "https://www.google.fr/maps/@44.8414409,-0.5694787,1283a,35y,39.11t/data=!3m1!1e3", id: "maps-location-link", target: '_blank' %>
        <%= link_to "Réserver", "https://www.airbnb.fr/rooms/6747273", class: "btn-xl"%>
      </div>
    </div>
  </section>
</div>

<div id="panel-right">
  <p class="panel-title">Descriptif complet des pièces</p>
  <p class="location-indication">Le logement est situé à 10 minutes à pied des quais et du centre</p>
  <% @flat.rooms.each_with_index do |room, i| %>
    <div id="<%= "room#{i}:#{room.name}" %>">
      <div class="room container-fluid">
        <p class="room-description"><%= room.description %></p>
        <div class="room-images-box row">
          <div class="col-6 text-center">
            <%= image_tag cl_image_path(room.photos[0].path), class: "room-image" %>
          </div>
          <div class="col-6 text-center">
            <%= image_tag cl_image_path(room.photos[1].path), class: "room-image" %>
          </div>
        </div>
        <%= link_to "cliquer pour agrandir les photos", "##{room.name}", class: "room-images-galery-link" %>
      </div>
    </div>
  <% end %>
</div>

<%= render "shared/photoswipe" %>

<%= content_for :after_js do %>
<script>
  $(document).ready(function(e) {
    $('.carousel-inner>.carousel-item:first-child').addClass("active")
    $('.carousel').carousel({
      interval: 3500,
      pause: "none"
    })

    $('#btn-rooms').on('click', function(e){
      console.log(e);
      $('#btn-rooms>span').toggleClass('fa-caret-down');
      $('#btn-rooms>span').toggleClass('fa-caret-up');
      $('#rooms-description-content').toggleClass('expand');
    });

    $('.room-images-galery-link').on('click', function(e){
      e.preventDefault();
      console.log(e);
      var items = [
        {
          src: $(this).parent().find('.room-image')[0].src,
          w: 1024,
          h: 683
        },
        {
          src: $(this).parent().find('.room-image')[1].src,
          w: 1024,
          h: 683
        }
      ];

      var gallery = new PhotoSwipe( $('.pswp')[0], PhotoSwipeUI_Default, items);
      gallery.init();
    });
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>House City Bordeaux</title>
    <link rel="shortcut icon" href=<%= image_url "favicon.png" %> type="image/x-icon">
    <%= csrf_meta_tags %>
    <%= yield(:metahead) %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>
  <body id="page-top" <%= yield(:body_tag) %>>
    <%= yield %>
    <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/shared/_photoswipe.html.erb
<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="pswp__bg"></div>
  <div class="pswp__scroll-wrap">
    <div class="pswp__container">
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
    </div>
    <div class="pswp__ui pswp__ui--hidden">
      <div class="pswp__top-bar">
        <div class="pswp__counter"></div>
        <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
        <button class="pswp__button pswp__button--share" title="Share"></button>
        <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
        <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
        <div class="pswp__preloader">
            <div class="pswp__preloader__icn">
              <div class="pswp__preloader__cut">
                <div class="pswp__preloader__donut"></div>
              </div>
            </div>
        </div>
      </div>
      <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
        <div class="pswp__share-tooltip"></div>
      </div>
      <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
      </button>

      <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
      </button>

      <div class="pswp__caption">
        <div class="pswp__caption__center"></div>
      </div>
    </div>
  </div>
</div>